[package]
name = "hecate"
version = "0.1.0"
authors = ["petitpenguin <ra1issa@bu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = { version = "0.5", default-features = false }
rand = "0.8.4"
sha2 = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
chrono = "0.4.19"
libsignal-protocol = {git = "https://github.com/Ra1issa/libsignal-client"}
signal-crypto = {git = "https://github.com/Ra1issa/libsignal-client"}
poksho = {git = "https://github.com/Ra1issa/libsignal-client"}


[dependencies.curve25519-dalek]
features = ["serde", "alloc"]
version = "3.0.0"
git = "https://github.com/signalapp/curve25519-dalek.git"
branch = "3.0.0-lizard2"

[profile.dev.package.num-bigint-dig]
opt-level = 2 # too slow otherwise!
