[package]
name = "hecate"
version = "0.1.0"
authors = ["petitpenguin <ra1issa@bu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = { version = "0.5", default-features = false }
rand = "0.8.4"
libsignal-protocol = {git = "https://github.com/Ra1issa/libsignal-client"}
poksho = {git = "https://github.com/Ra1issa/libsignal-client"}

[dependencies.curve25519-dalek]
features = ["serde", "alloc"]
version = "3.0.0"
git = "https://github.com/signalapp/curve25519-dalek.git"
branch = "3.0.0-lizard2"
